'''
Routines for outputting latex.

David Duvenaud
Nov 2012
'''

from datetime import datetime

def clean(string):
    '''Prepare a string for latex'''
    return string.replace('_', '').strip('1234567890')

def table(filename, rownames, colnames, entries, label=None):
    
    if label == None:
        label = filename.strip('/')[-1]

    rownames = [clean(s) for s in rownames]
    colnames = [clean(s) for s in colnames] 
    
    with open(filename, 'w') as file:

        # Print table header.
        file.write( '%% --- Automatically generated by latex.py ---\n')
        file.write( '%% Exported at %s\n' % str(datetime.now()))
        file.write( '\\begin{table}[h!]\n')
        file.write( '\\begin{center}\n')
        file.write( '\\begin{tabular}{l |%s}\n' % (' l' * len(colnames)))

        # Write first row.
        file.write( ' %s ' % colnames[0] )
        for c in range(1, len(colnames)):
            file.write( ' & \\rotatebox{0}{ %s } ' % colnames[c] )

        file.write( ' \\\\ \\hline\n' )

        # Write first column and table entries.
        for r in range(len(rownames)):
            file.write( rownames[r])
            for c in range(0, len(colnames) - 1):
                file.write( ' & %s ' % entries[r][c] )
            file.write( ' \\\\\n' )

        file.write( '\\end{tabular}\n');
        file.write( '\\end{center}\n');
        file.write( '\\label{tbl:%s}\n' % label)
        file.write( '\\end{table}\n');
