seed=0;   % fixing the seed of the random generators
randn('state',seed);
rand('state',seed);

n = 300;
x_max = 2;
data_folder = '../../data/synthetic-SNR-root-10/';

covs{1} = {@covSum, {...
                    {@covMask, {[1 0], {@covSEiso}}}, ...
                    {@covMask, {[0 1], {@covRQiso}}} ...
                    } ...
                    };
cov_params{1} = [1 0 -1 0 -1];
dims{1} = 2;
names{1} = 'SE1_p_RQ2.mat';
covs{2} = {@covProd,{...
                    {@covMask, {[1 0 0 0], {@covSEiso}}}, ...
                    {@covMask, {[0 1 0 0], {@covSEiso}}} ...
                    }...
                    };
cov_params{2} = [1 0 0 0];
dims{2} = 4;
names{2} = 'SE1_t_SE2.mat';
covs{3} = {@covSum ,{...
                    {@covMask, {[1 0 0], @covSEiso}}, ...
                    {@covProd, {...
                               {@covMask, {[1 0 0], {@covPeriodic}}},... 
                               {@covMask, {[0 1 0], {@covSEiso}}}...
                               }...
                    },...
                    {@covMask, {[0 0 1], @covSEiso}} ...
                    }...
                    };
cov_params{3} = [1 0 -1 -1 0 0 0 -1 0];
dims{3} = 3;
names{3} = 'SE1_p_Per1_t_SE2_p_SE3.mat';
covs{4} = {@covProd,{...
                    {@covSum, {...
                               {@covMask, {[1 0 0 0], {@covSEiso}}},... 
                               {@covMask, {[0 1 0 0], {@covSEiso}}}...
                               }...
                    },...
                    {@covSum, {...
                               {@covMask, {[0 0 1 0], {@covSEiso}}},... 
                               {@covMask, {[0 0 0 1], {@covSEiso}}}...
                               }...
                    }...
                    }...
                    };
cov_params{4} = [0 0 0 0 0 0 0 0];
dims{4} = 4;
names{4} = 'SE1_p_SE2_t_SE3_p_SE4.mat';
covs{5} = {@covSum, {...
                    {@covSEiso}, ...
                    {@covSEiso}, ...
                    {@covRQiso} ...
                    } ...
                    };
cov_params{5} = [1 0 -1 0 0 0 -2];
dims{5} = 1;
names{5} = 'SE1_p_SE1_p_RQ1.mat';
covs{6} = {@covProd,{...
                    {@covLINone}, ...
                    {@covPeriodic} ...
                    } ...
                    };
cov_params{6} = [0 0 -1 0];
dims{6} = 1;
names{6} = 'Lin1_t_Per1.mat';
covs{7} = {@covSum,{...
                    {@covProd, {...
                               {@covMask, {[1 0 0 0], {@covSEiso}}},... 
                               {@covMask, {[0 1 0 0], {@covSEiso}}}...
                               }...
                    },...
                    {@covProd, {...
                               {@covMask, {[0 1 0 0], {@covSEiso}}},... 
                               {@covMask, {[0 0 1 0], {@covSEiso}}}...
                               }...
                    }...
                    }...
                    };
cov_params{7} = [0 0 1 0 -1 0 0 0];
dims{7} = 4;
names{7} = 'SE1_t_SE2_p_SE2_t_SE3.mat';
covs{8} = {@covSum, {...
                    {@covSEiso}, ...
                    {@covRQiso} ...
                    } ...
                    };
cov_params{8} = [0 0 -1 0 -2];
dims{8} = 1;
names{8} = 'SE1_p_RQ1.mat';

for i = 1:length(covs)
    X = (rand(n,dims{i})-0.5)*2*x_max;
    K = feval(covs{i}{:}, cov_params{i}, X);
    K = K +  1e-6*eye(n);
    y = chol(K)' * randn(n,1);
    y = y - mean(y);
    y = y / std(y);
    y = y + randn(size(y)) / sqrt(10);
    save([data_folder names{i}], 'X', 'y');
end